Add: upgraded publish action

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -50,8 +50,12 @@ jobs:
                       break;
                   fi
               done
-          elif [ ${{ env.branch }} == 'master' ]; then
+          elif [ ${{ env.branch }} == 'main' ]; then
               echo "npm_tag_version=latest" >> $GITHUB_ENV
+              if git tag --list | grep -q "^${{ env.tag_version }}$"; then
+                echo "Error: Tag ${{ env.tag_version }} already exists"
+                exit 1
+              fi
           elif [ `git tag --list | grep -q ${{ env.tag_version }}` -ne 0 ]; then exit 1; fi
 
       - name: Update package.json version, package-lock.json and commit
